- name: Descargar repositorio
  template:
    src: git.sh.j2
    dest: /root/git.sh
    owner: root
    group: root
    mode: 755

- name: Ejecutar script git.sh
  shell: /root/git.sh
  args:
    creates: "/var/www/html/proyecto/{{ item }}"
