- name: Instalar Mysql
  apt: name=mysql-server state=latest
- name: Ejecutamos script
  script: ./files/uname.sh
- name: Instalar pip
  apt: name=python3-pip state=latest
- name: Instalar modulo pexecpt con pip
  command: pip3 install pexpect==3.3
#- name: Secure MySQL Installation
#  expect:
#    command: /usr/bin/mysql_secure_installation
#    responses:
#      'Enter password for user root\:': "1234"
#      'Re-enter new password\:': "1234"
#      'Remove anonymous users\? \[Y/n\]': "y"
#      'Disallow root login remotely\? \[Y/n\]': "y"
#      'Remove test database and access to it\? \[Y/n\]': "n"
#      'Reload privileges tables now\? \[Y/n\]': "n"
- name: Instalamos pymsql
  command: pip3 install pymysql
- name: copy .my.cnf file with root password credentials
  template: src=mysql.exp dest=/root/mysql.exp owner=luis mode=0600
- name: Copiamos
  template: src=Jardineria.sql dest=/root/Jardineria.sql owner=luis mode=0600
- name: Ejecutar el expect de mysql
  command: expect /root/mysql.exp
  ignore_errors: true
- name: restart mysql
  service: name=mysql state=restarted
#- name: Cambiar contraseña de usuario
#  expect:
#    command: /usr/bin/mysql_secure_installation
#    responses: 
      #ERegular para indicar que password puede estar en mayus/minus
#      Press y|Y for Yes, any other key for No: "n"
#      New password: "1234"
#      Re-enter new password: "1234"
#      Remove anonymous users? (Press y|Y for Yes, any other key for No): "n"
#      Disallow root login remotely? (Press y|Y for Yes, any other key for No): "y"
#      Remove test database and access to it? (Press y|Y for Yes, any other key for No): "n"
#      Reload privilege tables now? (Press y|Y for Yes, any other key for No): "n"    
#- name: Cambiar contraseña de usuario
#  expect:
#    command: passwd usuario1
#    responses: 
      #ERegular para indicar que password puede estar en mayus/minus
 #     (?i)password: "Passw0rd" 
#- name: Generic question with multiple different responses
#  expect:
#    command: /usr/bin/mysql_secure_installation
#    responses:
#      Question:
#        - 1234
#        - 1234
#        - n
#        - y
#        - n
#        - n
#- name: Configuramos el root
#  mysql_user:
#    login_host: localhost
#    login_user: root
#    login_password: ''
#    name: root
#    password: 1234
#    login_unix_socket: /var/run/mysqld/mysqld.sock
#    state: present
#  ignore_errors: true


#- name: update mysql root password for all root accounts
#  mysql_user: name=root host=localhost password=1234 priv=*.*:ALL,GRANT login_unix_socket=/var/run/mysqld/mysqld.sock check_implicit_admin=true
#  ignore_errors: true
#- name: delete anonymous MySQL server user for $server_hostname
#  action: mysql_user user="" host="pc2" state="absent"
#- name: delete anonymous MySQL server user for localhost
#  action: mysql_user user="" login_user=root login_password=1234 state="absent"
#- name: remove the MySQL test database
#  action: mysql_db db=test login_user=root login_password=1234 state=absent
